[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"

[[outputs.graphite]]
  servers = ["graphite:2003"]
  prefix = "techfest"
  graphite_tag_support = false

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.mem]]

[[inputs.net]]

[[inputs.system]]